### PR TITLE
Review/5108

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/EtaExpansion.scala [hunk 1]
```diff
@@ -99,7 +99,7 @@ trait EtaExpansion { self: Analyzer =>
 
     /* Eta-expand lifted tree. */
     def expand(tree: Tree, tpe: Type): Tree = tpe match {
-      case mt @ MethodType(paramSyms, restpe) if !mt.isImplicit =>
+      case mt @ MethodType(paramSyms, restpe) if !mt.isImplicit => //
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/EtaExpansion.scala]: looks okay, could do with a test:

```
scala> {def bar(a: Int)(implicit b: DummyImplicit)(implicit c: DummyImplicit) = 0; bar _} //print

{
  def bar(a: scala.Int)(implicit b: scala.Predef.DummyImplicit)(implicit c: scala.Predef.DummyImplicit) = 0;
  {
    ((a: Int) => bar(a)(Predef.this.DummyImplicit.dummyImplicit)(Predef.this.DummyImplicit.dummyImplicit))
  }
} // : Int => Int
```

File: src/compiler/scala/tools/nsc/typechecker/Implicits.scala [hunk 2]
```diff
@@ -538,7 +538,7 @@ trait Implicits {
     private def checkCompatibility(fast: Boolean, tp0: Type, pt0: Type): Boolean = {
       @tailrec def loop(tp: Type, pt: Type): Boolean = tp match {
         case mt @ MethodType(params, restpe) =>
-          if (mt.isImplicit)
+          if (mt.isImplicit) //
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/Implicits.scala]: The crux: this will now unwrap all implicit method types to get to the result type, so the following works:

```
scala> {class A; implicit def bar(implicit b: DummyImplicit)(implicit c: DummyImplicit): A = new A; implicitly[A]} //print

{
  class A;
  implicit def bar(implicit b: scala.Predef.DummyImplicit)(implicit c: scala.Predef.DummyImplicit): A = new A();
  scala.Predef.implicitly[A](bar(Predef.this.DummyImplicit.dummyImplicit)(Predef.this.DummyImplicit.dummyImplicit))
} // : A
```

File: src/compiler/scala/tools/nsc/typechecker/Infer.scala [hunk 3]
```diff
@@ -148,7 +148,7 @@ trait Infer extends Checkable {
   }
 
   def skipImplicit(tp: Type) = tp match {
-    case mt: MethodType if mt.isImplicit  => mt.resultType
+    case mt: MethodType if mt.isImplicit  => mt.resultType //
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/Infer.scala]: - [ ] This looks like a potential bug with more than one implicit param list

`skipImplicit` is called from this error message:

```
scala> def foo[A](implicit a: DummyImplicit): Array[A] = null
foo: [A](implicit a: DummyImplicit)Array[A]

scala> foo: Seq[_]
<console>:18: error: polymorphic expression cannot be instantiated to expected type;
 found   : [A]Array[A]
 required: Seq[_]
       foo: Seq[_]
       ^

scala> def foo[A](implicit a: DummyImplicit)(implicit b: DummyImplicit): Array[A] = null
foo: [A](implicit a: DummyImplicit)(implicit b: DummyImplicit)Array[A]

scala> foo: Seq[_]
<console>:18: error: polymorphic expression cannot be instantiated to expected type;
 found   : [A](implicit b: DummyImplicit)Array[A]
 required: Seq[_]
       foo: Seq[_]
       ^
```

It is also called from `Infer::inferForApproxPt` as follows (in the context of inferring type paramsters for constructor patterns for case classes:

```
val resTpInst  = skipImplicit(ctorTpInst.finalResultType)
```

However, AFAICT the call to `finalResultType` would peel off all `MethodTypes` rendering `skipImplicit` a redundant no-op.

File: src/compiler/scala/tools/nsc/typechecker/Infer.scala [hunk 4]
```diff
@@ -163,7 +163,7 @@ trait Infer extends Checkable {
       logResult(sm"""|Normalizing PolyType in infer:
                      |  was: $restpe
                      |  now""")(normalize(restpe))
-    case mt @ MethodType(_, restpe) if mt.isImplicit             => normalize(restpe)
+    case mt @ MethodType(_, restpe) if mt.isImplicit             => normalize(restpe) //
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/Infer.scala]: LGTM, will recurse to strip off all implicit param lists.

File: src/compiler/scala/tools/nsc/typechecker/Infer.scala [hunk 5]
```diff
@@ -366,7 +366,7 @@ trait Infer extends Checkable {
       // optimize type variables wrt to the implicit formals only; ignore the result type.
       // See test pos/jesper.scala
       def variance = restpe match {
-        case mt: MethodType if mt.isImplicit && isFullyDefined(pt) => MethodType(mt.params, AnyTpe)
+        case mt: MethodType if mt.isImplicit && isFullyDefined(pt) => MethodType(mt.params, AnyTpe) //
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/Infer.scala]: LGTM, we'll ignore all implicit param lists, rather than the only one, when approximating the type used to calculate the variance (and direction of solving) of the type params

File: src/compiler/scala/tools/nsc/typechecker/Infer.scala [hunk 6]
```diff
@@ -811,21 +811,21 @@ trait Infer extends Checkable {
...
         case et: ExistentialType                                            => isAsSpecific(et.skolemizeExistential, ftpe2)
         case NullaryMethodType(restpe)                                      => isAsSpecific(restpe, ftpe2)
-        case mt @ MethodType(_, restpe) if mt.isImplicit                    => isAsSpecific(restpe, ftpe2)
+        case mt @ MethodType(_, restpe) if mt.isImplicit                    => isAsSpecific(restpe, ftpe2) //
         case mt @ MethodType(_, _) if bothAreVarargs                        => checkIsApplicable(mt.paramTypes mapConserve repeatedToSingle)
         case mt @ MethodType(params, _) if params.nonEmpty                  => checkIsApplicable(mt.paramTypes)
         case PolyType(tparams, NullaryMethodType(restpe))                   => isAsSpecific(PolyType(tparams, restpe), ftpe2)
-        case PolyType(tparams, mt @ MethodType(_, restpe)) if mt.isImplicit => isAsSpecific(PolyType(tparams, restpe), ftpe2)
+        case PolyType(tparams, mt @ MethodType(_, restpe)) if mt.isImplicit => isAsSpecific(PolyType(tparams, restpe), ftpe2) //
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/Infer.scala]: - [ ] This looks like it needs to be updated to;

```
case mt @ MethodType(_, _) if mt.isImplicit                    => isAsSpecific(skipImplicit(mt), ftpe2)
...
case PolyType(tparams, mt @ MethodType(_, _)) if mt.isImplicit => isAsSpecific(PolyType(tparams, skipImplicit(mt)), ftpe2)
```

With a test to show that overload resolution behaves the same for 1 and N implicit param lists (ie, it ignores the implicit params)

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 7]
```diff
@@ -1165,7 +1165,7 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
           notifyUndetparamsAdded(tparams1)
           adapt(tree1 setType restpe.substSym(tparams, tparams1), mode, pt, original)
 
-        case mt: MethodType if mode.typingExprNotFunNotLhs && mt.isImplicit => // (4.1)
+        case mt: MethodType if mode.typingExprNotFunNotLhs && mt.isImplicit => // (4.1) //
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: LGTM, adaptation should happen one param lists at a time.

File: src/interactive/scala/tools/nsc/interactive/Global.scala [hunk 8]
```diff
@@ -1079,7 +1079,7 @@ class Global(settings: Settings, _reporter: Reporter, projectName: String = "")
     val context = doLocateContext(pos)
     val shouldTypeQualifier = tree0.tpe match {
       case null           => true
-      case mt: MethodType => mt.isImplicit
+      case mt: MethodType => mt.isImplicit //
```
Comment (retronym) [inline src/interactive/scala/tools/nsc/interactive/Global.scala]: Not sure, probably okay.

File: src/reflect/scala/reflect/internal/TreeInfo.scala [hunk 9]
```diff
@@ -268,7 +268,7 @@ abstract class TreeInfo {
   def mayBeVarGetter(sym: Symbol): Boolean = sym.info match {
     case NullaryMethodType(_)              => sym.owner.isClass && !sym.isStable
     case PolyType(_, NullaryMethodType(_)) => sym.owner.isClass && !sym.isStable
-    case mt @ MethodType(_, _)             => mt.isImplicit && sym.owner.isClass && !sym.isStable
+    case mt @ MethodType(_, _)             => mt.isImplicit && sym.owner.isClass && !sym.isStable //
     case _                                 => false
   }
```
Comment (retronym) [inline src/reflect/scala/reflect/internal/TreeInfo.scala]: Okay, here's a test case:

```
scala> object O { def a(implicit I: DummyImplicit) = 42; def a_=(a: Any) = () }; O.a = 0
defined object O
O.a: Int = 42

scala> object O { def a(implicit I: DummyImplicit)(implicit J: DummyImplicit) = 42; def a_=(a: Any) = () }; O.a = 0
defined object O
O.a: Int = 42
```

File: src/reflect/scala/reflect/internal/Types.scala [hunk 10]
```diff
@@ -4025,7 +4025,7 @@ trait Types
   }
 
   def isImplicitMethodType(tp: Type) = tp match {
-    case mt: MethodType => mt.isImplicit
+    case mt: MethodType => mt.isImplicit //
     case _              => false
   }
```
Comment (retronym) [inline src/reflect/scala/reflect/internal/Types.scala]: LGTM

File: src/reflect/scala/reflect/internal/Types.scala [hunk 11]
```diff
@@ -4219,7 +4219,7 @@ trait Types
         tp2 match {
           case mt2 @ MethodType(params2, res2) =>
             // sameLength(params1, params2) was used directly as pre-screening optimization (now done by matchesQuantified -- is that ok, performancewise?)
-            mt1.isImplicit == mt2.isImplicit &&
+            mt1.isImplicit == mt2.isImplicit && //
```
Comment (retronym) [inline src/reflect/scala/reflect/internal/Types.scala]: The existing implementation looks suspicious to me, it allows one to override a method without the `override` modifier:

```
scala> class C[T >: Null] { def a(implicit i: T = null): Any = "C"}; class S extends C[String] { def a(i: String) = "S" }
defined class C
defined class S

scala> (new S() : C[String]).a()
res8: Any = S
```

My intuition is that `matchesType` should ignore implicit modifers when determining overriding relationships, and a separate check in refchecks should enforce that the overriding method has the same implicit modiifier (or modifiers!) as the overriden one.

File: src/reflect/scala/reflect/internal/tpe/TypeComparers.scala [hunk 12]
```diff
@@ -157,7 +157,7 @@ trait TypeComparers {
   private def isSameMethodType(mt1: MethodType, mt2: MethodType) = (
        isSameTypes(mt1.paramTypes, mt2.paramTypes)
     && (mt1.resultType =:= mt2.resultType.substSym(mt2.params, mt1.params))
-    && (mt1.isImplicit == mt2.isImplicit)
+    && (mt1.isImplicit == mt2.isImplicit) //
```
Comment (retronym) [inline src/reflect/scala/reflect/internal/tpe/TypeComparers.scala]: LGTM, this will recurse as needed.

File: src/reflect/scala/reflect/internal/tpe/TypeComparers.scala [hunk 13]
```diff
@@ -489,7 +489,7 @@ trait TypeComparers {
             val params2 = mt2.params
             val res2 = mt2.resultType
             (sameLength(params1, params2) &&
-              mt1.isImplicit == mt2.isImplicit &&
+              mt1.isImplicit == mt2.isImplicit && //
```
Comment (retronym) [inline src/reflect/scala/reflect/internal/tpe/TypeComparers.scala]: LGTM

```
scala> object O { def a(implicit I: DummyImplicit)(implicit J: DummyImplicit) = 42};
defined object O

scala> object P { def a(implicit I: DummyImplicit)(implicit J: DummyImplicit) = 42};
defined object P

scala> object Q { def a(implicit I: DummyImplicit)(implicit J: Int) = 42};
defined object Q

scala> val List(mt1, mt2, mt3) = List(typeOf[O.type], typeOf[P.type], typeOf[Q.type]).map(_.member(TermName("a")).info)
mt1: $r.intp.global.Type = (implicit I: DummyImplicit)(implicit J: DummyImplicit)Int
mt2: $r.intp.global.Type = (implicit I: DummyImplicit)(implicit J: DummyImplicit)Int
mt3: $r.intp.global.Type = (implicit I: DummyImplicit)(implicit J: Int)Int

scala> mt2 =:= mt1
res16: Boolean = true

scala> mt2 =:= mt3
res17: Boolean = false

scala> mt2 <:< mt1
res18: Boolean = true

scala> mt2 <:< mt3
res19: Boolean = false
```

File: src/compiler/scala/tools/nsc/typechecker/Infer.scala (hunk 3 above)
Comment (milessabin) [inline src/compiler/scala/tools/nsc/typechecker/Infer.scala]: Can you explain the issue here a little more for me? If I try,
```
def foo[A](a: DummyImplicit)(implicit b: DummyImplicit): Array[A] = null
foo: Seq[_]
```
(ie. your second example but with the first parameter list not implicit) I see the exact same error as with both parameter list implicit,
```
multi-implicits.scala:81: error: polymorphic expression cannot be instantiated to expected type;
 found   : [A](a: DummyImplicit)(implicit b: DummyImplicit)Array[A]
 required: Seq[_]
    foo: Seq[_]
    ^
```
Are you saying the the call to `skipImplicit` should just be removed? And instead we should just have,
```
val resTpInst  = ctorTpInst.finalResultType
```

Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/Infer.scala]: Yes, my reading of this code is that `skipImplicit` is a no-op, because `finalResultType` already strips all `MethodType`s.

Looks like `finalResultType` was introduced in https://github.com/scala/scala/commit/b9082321219f78a86e80fcea2a71d96ee4beb397#diff-62ccdfe29e58b8e9f06ed66d4cfc88a5L1086 / https://github.com/scala/scala/commit/b9082321219f78a86e80fcea2a71d96ee4beb397#diff-62ccdfe29e58b8e9f06ed66d4cfc88a5R1092

File: src/compiler/scala/tools/nsc/typechecker/Infer.scala (hunk 6 above)
Comment (milessabin) [inline src/compiler/scala/tools/nsc/typechecker/Infer.scala]: Can you say a little more about the overloading scenario you would expect to distinguish these two implementations? I've tried the following,
```
bject Overload1 {                                                                                                                    
  def over(i: Int)(implicit d: DummyImplicit): Int = i
  def over(b: Boolean)(implicit d: DummyImplicit): Boolean = b

  (over(23): Int)
  (over(true): Boolean)
}

object Overload2 {
  def over(i: Int)(implicit d: DummyImplicit)(implicit e: DummyImplicit): Int = i
  def over(b: Boolean)(implicit d: DummyImplicit)(implicit e: DummyImplicit): Boolean = b

  (over(23): Int)
  (over(true): Boolean)
}
```
and both appear to compile the same way with both implementations.
